### ISSUE TITLE
Default context below required minimum

### ISSUE THREAD

**Issue by tommai78101** [JulianStambuk/Newtonian-Particle-Simulator#3]
Per the issue mentioned in #2, I need to modify the `MainWindow` class object and insert an `NativeWindowSettings` override to change the core version to the version necessary to run this application. (Requested 4.5, got back a core 3.30 version on RTX 2070 as the default, have to provide an override to get 4.6.)

@JulianStambuk mentioned the following:

> Turns out on my system requesting 4.6 returns a Core Profile which means rendering without an VAO wont work anymore (deprecated in core). I could specifically request a Compatibility Context but I am not sure about that.

And this may affect how rendering works if the requested OpenGL version is not properly requested going forward.

(Please feel free to update the issue title.)

**Comment by BoyBaykiller** [comment]
Thanks for creating a dedicated issue.

I would go for the following:
```cs
public MainWindow() 
    : base(
          832, 832,
          new GraphicsMode(0, 0, 0, 0),
          "Newtonian-Particle-Simulator",
          GameWindowFlags.Default,
          DisplayDevice.Default,
          4, 6, // major, minor
          GraphicsContextFlags.Default) 
{

}
```
Or what is it that you tried? After all there is no overload of the `GameWindow` constructor, which is the base class, that has `NativeWindowSettings` as a parameter.

As I said this may also return a `core` profile which means I will have to create a dummy vao and bind that (currently rendering without any vao which is deprecated in `4.6 core`). This will of course work on `Core` and `Compatibility`. I would much rather request a `compatibility` profile, but I dont know if its safe to assume that you will actually get one. Anyways let me know if that works.

**Comment by tommai78101** [comment]
Just pulled the source code down, used Visual Studio 2022 to build a Release build.

The first thing the Release build does is, it complains about missing shader files.

I had to go to `Newtonian-Particle-Simulator\bin\Release\net5.0\`, create new folder `.\res\shaders\particles\`, and then manually copy the shader files (fragment + vertex shaders) to the `particles` folder.

![image](https://user-images.githubusercontent.com/6444116/154389723-fda1a6f2-ce67-4d94-941e-5f4ce1f46d91.png)

After that, it works out of the box. Was able to grab an OpenGL 4.6 context, so it's all good now.

**Comment by BoyBaykiller** [comment]
The [working directory of the project](https://github.com/BoyBaykiller/Newtonian-Particle-Simulator/blob/master/Newtonian-Particle-Simulator/Properties/launchSettings.json) is set to the same level where `res` is so as long as you start the application through VS it should be all fine. You can let me know if you found out why VS doesn't respect the working dir for you. I've not been able to reproduce this. 
But good to hear the context thing is no longer a problem so I think I can close this one.
