### ISSUE TITLE
Does not works with the latest version(s) of OpenTk

### ISSUE THREAD

**Issue by MahmudX** [JulianStambuk/Newtonian-Particle-Simulator#4]
I updated the `OpenTk` version to 4.7.4 and the app does not run. Many classes such as `GraphicsMode` throws error. Can you please update the repo compatible with current version?
.
Love your works man.

**Comment by BoyBaykiller** [comment]
Hi.
Thats to be expected since every major release in OpenTK contains breaking changes.
While I do use OpenTK 4.7.4 in newer projects, I dont see much value in updating from version 3.3.2 here.
